title: Product
files:
  template: product

columns:
  - width: 1/2
    fields:
      product:
        label: Product
        type: files
        layout: cards
        cover: true
        width: 1/1

  - width: 1/3
    fields:
      name:
        label: Title
        type: text

      description:
        label: Type
        type: text

      price:
        type: editor
        size: small

      sale:
        type: editor
        size: small

      link:
        type: url
        width: 1/2
