title: Project
files:
  template: project

columns:

 - width: 1/1
  fields:
      year:
        label: Year
        type: number
        width: 1/4
      client:
        label: Client
        type: text
        width: 1/4

 - width: 1/2
  fields:
   tags:
    label: Media
    type: tags
    options:
          poster: Poster
          editorial: Editorial
          branding: Branding
          curation: Curation
          typeface: Typeface
          other: Other
 - width: 1/2
  fields:
   description:
    label: Description
    type: editor
    size: large

 - width: 2/2
   fields:
      builder:
         label: Slider
         type: builder
         columns: 3 # Optional. If set to 2 or more, the builder blocks will be placed in a grid.
         fieldsets:
           slider: # This is a field set. It contains a group of kirby fields. The user can select from these sets to build the content.
               label: Landscape
               snippet: builder/slider  # The name option is used as a label for the buttons to add new fieldsets. It is also used as a label in the header of the fieldset, if the label option is not set explicitly (see next line). 
               fields:
                 images:
                   label: Image collection
                   type: files
                   layout: list
                   template: project
                   query: page.files
                   text: "{{ file.caption}}"
           portrait: # This is a field set. It contains a group of kirby fields. The user can select from these sets to build the content.
               label: Portrait
               snippet: builder/portrait # The name option is used as a label for the buttons to add new fieldsets. It is also used as a label in the header of the fieldset, if the label option is not set explicitly (see next line). 
               fields:
                 images2:
                   label: Image collection portrait
                   type: files
                   layout: list
                   template: project
                   query: page.files
                   text: "{{ file.caption}}"





     

                
                  

               
              


              
       
               
               